apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "photo-critique.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "photo-critique.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "photo-critique.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      labels:
        {{- include "photo-critique.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      serviceAccountName: {{ include "photo-critique.fullname" . }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
          resources:
            limits:
              cpu: "{{ .Values.backend.resources.limits.cpu }}"
              memory: "{{ .Values.backend.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.backend.resources.requests.cpu }}"
              memory: "{{ .Values.backend.resources.requests.memory }}"
          envFrom:
            - configMapRef:
                name: {{ include "photo-critique.fullname" . }}-config