apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "photo-critique.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "photo-critique.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/component: backend
        {{- include "photo-critique.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "photo-critique.fullname" . }}-sa
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ include "photo-critique.fullname" . }}-config
          resources:
            limits:
              cpu: "{{ .Values.resources.backend.limits.cpu }}"
              memory: "{{ .Values.resources.backend.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.backend.requests.cpu }}"
              memory: "{{ .Values.resources.backend.requests.memory }}"