apiVersion: v1
kind: Service
metadata:
  name: {{ include "photo-critique.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "photo-critique.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "photo-critique.selectorLabels" . | nindent 4 }}
    component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}