apiVersion: v1
kind: Service
metadata:
  name: {{ include "photo-critique.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "photo-critique.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
      protocol: TCP
      name: http