{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "photo-critique.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "photo-critique.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "photo-critique.fullname" $. }}-{{ if contains "backend" .host }}backend{{ else }}frontend{{ end }}
                port:
                  number: {{ if contains "backend" .host }}{{ $.Values.backend.service.port }}{{ else }}{{ $.Values.frontend.service.port }}{{ end }}
          {{- end }}
    {{- end }}
  #tls:
  #  - hosts:
  #      - backend.example.com
  #      - frontend.example.com
  #    secretName: {{ include "photo-critique.fullname" . }}-tls
{{- end }}