apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "photo-critique.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "photo-critique.labels" . | nindent 4 }}