apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photo-critique-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Navneet072300/photo-critique.git
    targetRevision: dev
    path: helm
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: photo-critique-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true