backend:
  replicaCount: 3
  image:
    tag: "{{ env \"GIT_SHA\" }}"
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  service:
    port: 8000
    targetPort: 8000

frontend:
  replicaCount: 3
  image:
    tag: "{{ env \"GIT_SHA\" }}"
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  service:
    port: 3000
    targetPort: 3000

ingress:
  enabled: true